ALTER TABLE users ADD COLUMN email VARCHAR(254) NOT NULL DEFAULT '';
ALTER TABLE users ADD CONSTRAINT uq_users_email UNIQUE (email);
ALTER TABLE users ALTER COLUMN email DROP DEFAULT;

ALTER TABLE users ADD COLUMN phone_number VARCHAR(20);
ALTER TABLE users ADD CONSTRAINT uq_users_phone_number UNIQUE (phone_number);
